name: coin_venture
description: Flutter crypto exchange application using Clean Architecture and BLoC.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.7
  injectable: ^2.3.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  dio: ^5.4.0
  dio_smart_retry: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.15.5
  google_sign_in: ^6.1.6
  local_auth: ^2.1.7
  go_router: ^13.1.0
  intl: ^0.18.1
  fl_chart: ^0.66.1
  cached_network_image: ^3.3.1
  collection: ^1.18.0

  # Optional utilities
  logger: ^2.0.2+1

  # Web specific
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.2
  bloc_test: ^9.1.5
  mocktail: ^1.0.3
  golden_toolkit: ^0.15.0

