// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcMXkwN3hc9GOv3ZiW5Hcd0ySNGASMjfQ',
    appId: '1:414601306551:web:6cc1cb72c484c42e108832',
    messagingSenderId: '414601306551',
    projectId: 'coin-venture-4eec3',
    authDomain: 'coin-venture-4eec3.firebaseapp.com',
    databaseURL: 'https://coin-venture-4eec3-default-rtdb.firebaseio.com',
    storageBucket: 'coin-venture-4eec3.firebasestorage.app',
    measurementId: 'G-GRTFDYJP11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBNswzkqsKXmjmyrLpzXhsMALSskFNZSY',
    appId: '1:414601306551:android:d4e638c5c60f27f7108832',
    messagingSenderId: '414601306551',
    projectId: 'coin-venture-4eec3',
    databaseURL: 'https://coin-venture-4eec3-default-rtdb.firebaseio.com',
    storageBucket: 'coin-venture-4eec3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu8udEUrbmut4KgOuNg7NEPjox7emW2-U',
    appId: '1:414601306551:ios:f02dbb7e4f02f196108832',
    messagingSenderId: '414601306551',
    projectId: 'coin-venture-4eec3',
    databaseURL: 'https://coin-venture-4eec3-default-rtdb.firebaseio.com',
    storageBucket: 'coin-venture-4eec3.firebasestorage.app',
    iosClientId: '414601306551-i4hh5tg393k7hua545etp8cmlhqdl5dn.apps.googleusercontent.com',
    iosBundleId: 'com.example.coinVenture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu8udEUrbmut4KgOuNg7NEPjox7emW2-U',
    appId: '1:414601306551:ios:f02dbb7e4f02f196108832',
    messagingSenderId: '414601306551',
    projectId: 'coin-venture-4eec3',
    databaseURL: 'https://coin-venture-4eec3-default-rtdb.firebaseio.com',
    storageBucket: 'coin-venture-4eec3.firebasestorage.app',
    iosClientId: '414601306551-i4hh5tg393k7hua545etp8cmlhqdl5dn.apps.googleusercontent.com',
    iosBundleId: 'com.example.coinVenture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcMXkwN3hc9GOv3ZiW5Hcd0ySNGASMjfQ',
    appId: '1:414601306551:web:22c1300cba64665a108832',
    messagingSenderId: '414601306551',
    projectId: 'coin-venture-4eec3',
    authDomain: 'coin-venture-4eec3.firebaseapp.com',
    databaseURL: 'https://coin-venture-4eec3-default-rtdb.firebaseio.com',
    storageBucket: 'coin-venture-4eec3.firebasestorage.app',
    measurementId: 'G-WHXCN1263B',
  );
}
